name: Build flake packages
on:
  # schedule:
  #   - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Evaluate flake
      run: .github/scripts/eval.sh --flake .#packages.x86_64-linux

    - name: Use attic cache
      run: |
        nix profile install nixpkgs#attic-client
        attic login --set-default dev https://cache.ataraxiadev.com/ ${{ secrets.ATTIC_TOKEN }}
        attic use ataraxiadev

    - name: Build packages
      run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --flake .#packages.x86_64-linux

    - name: Upload to attic
      run: attic push ataraxiadev ./result*