name: Update flake.lock
on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Import GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6.1.0
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Install nix
      uses: cachix/install-nix-action@V28

    - name: Update flake
      run: nix flake update

    - name: Evaluate flake
      run: .github/scripts/eval.sh --flake .#packages.x86_64-linux

    - name: Commit updated flake.lock
      run: |
        git commit -m "chore: update flake.lock" flake.lock
      env:
        GIT_AUTHOR_NAME: AtaraxiaSjel
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: AtaraxiaSjel
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}

    - name: Push flake.lock
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}